name: hive_example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  get_it: ^7.7.0
  vexana: ^4.1.0
  dio_nexus: ^0.2.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
